[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Mantle Network Configuration
[rpc_endpoints]
# Mantle Testnet
mantle_testnet = "https://rpc.sepolia.mantle.xyz"
testnet = "${RPC_URL}"

# Mantle Mainnet
mantle_mainnet = "https://rpc.mantle.xyz"
mainnet = "https://rpc.mantle.xyz"

# Local development
local = "http://localhost:8545"

[etherscan]
# Mantle Testnet
mantle_testnet = { key = "${MANTLE_EXPLORER_API_KEY}", chain = 5003, url = "https://explorer.sepolia.mantle.xyz/api" }
testnet = { key = "${MANTLE_EXPLORER_API_KEY}", chain = 5003, url = "https://explorer.sepolia.mantle.xyz/api" }

# Mantle Mainnet
mantle_mainnet = { key = "${MANTLE_EXPLORER_API_KEY}", chain = 5000, url = "https://explorer.mantle.xyz/api" }
mainnet = { key = "${MANTLE_EXPLORER_API_KEY}", chain = 5000, url = "https://explorer.mantle.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
